apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uLgbcR+s+9KI80o4L/fE5TH/cuDl2DiYNtg6lhan7cC0dl9arloOUg==,iv:x8NIDiyBtm29yuLwGHQZygbY92+HxUkIWigLPfKid14=,tag:rxtlaju41J5p5jMW/HMcSA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VzMxcGxHWVNOaEg2Z2tV
            QzhIMUMzNFhPQVZtSTFuVUZwMENaeWhPeDIwCkFyM1lvUGp0QjFaeGdlQWkwanVN
            UFZ1c1FIUlg0OW92Y2dKdS9waU9XQ1UKLS0tIHVxUitMbXFMQ1B0ZE96ZVNBbzZW
            RXIvVVhoWGNCejlkWkxoUnh1d3hIWG8K8QmU46xg7vdmKnP9C1jV0WfZz4CJrR16
            IAB7E0qUy8+y8SKdIyF51N26DwXTzCRNqxOkrt2DwtIGoliH4pywIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:41:09Z"
    mac: ENC[AES256_GCM,data:2o0GoI55Lnmq6HypuyZsfXIOqkjV8PErKP0ewuZ6iZk/jcZIeYAlfAxuCWQjHArSFVF+RNuTYJlLrwASxZ37LkMPBrLuUxkrINY/dwyxhrkCCYj6A2YOHdRreS+/Wi36sfdPcFTchhVum3GMVyk9cc+6VP1MwHBO6Ws4taljts4=,iv:wUBDBZVK8dB4Sw7x1t2P2i6WIe558UBFTflo4/QmKfk=,tag:cuZkx6ZLrtfy7IbbbBl0Pg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
