apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oQT2YK5tB6shRwJYAZB3RgU6Gc/wvrn8cyHGkDu0j5sV7M2iCWVUfA==,iv:maSnl+ifO7r72sx0njEjCKAMPGykZVV8K96psClrfX8=,tag:Hma+E5nGS6im+o/b8j2YAg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNFVYSUtEb1huVW11UVll
            NjRmaHZnRU84VTNrMzVDUU9uQlFWZm5Zbms0CmNYdGFQR3FMMit5QW1uS0VCbTBv
            Z0lDVWM5eWRWbTM2N0ZkdDExME1INmMKLS0tIGR1eTZWY09UdWg5a05aNTdmcURL
            aExrWW93MmFMSzR3RUthQnRvajNiYXMK/1FsUkfqiQ7mKodU9EkmZ7xRZy4hTaE5
            0qb9cDw1A/vwhxkBSC66oE2eDvjFWjEGozcjfxk88ci6jguqIdEGwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T12:28:03Z"
    mac: ENC[AES256_GCM,data:nADVHHvYRnR1DpoK3VHMEQJdrm0QbQUvFsO/C7u5GGfDVPNugXDbl1qXJru3HdtvrWcGconrhlg+QTmZhJPRnRdm4UuRgBpiJH/tiCNokxtu141uzV41+k5V1AaLILEK6cb7vLUt2/449RdRmTJCDhglpPoGoWJo4hNS1miBV5o=,iv:Q4HlZ88ksV/E+BLYLcLt+pZDsdpzcV74goSlQnyoN9k=,tag:8026e4zUMbItFSbUeFWYeg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
