apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MIUyBR9ZDhwp5OhFkFH2aZ4rOdu4vPxAvEmzqw+wq/vkPwFwZNFToQ==,iv:HKjpo1js0SUf01GPAhhZuiYzVD055qwMNhapguLVqzg=,tag:2QFWTFZubErJyJ/8AeAxmQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2NKay92eUhZQlpkdUkw
            Rlg5dWtGQWZvbjZwSGNpNmRZOU56NmJaWkQ4CkNjYStST2dzUWVZNzUxZ2l0L21Y
            MllZNGpURC9qMm5HZmRENFV5MTZZT1EKLS0tIFQralFMOUpJbFVyOFFCT3EwSjRP
            NG1YR1RTQVJBTnFycmU1UFFBczJJUUkKWHJBdnDtDQK/BT53lN/jcpFlxQJqsjOo
            GsvHStQQOqoBrXFTPa52k4p4qhMBX+EyUijg4f6tNaEU5fm2kRdnyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T09:16:47Z"
    mac: ENC[AES256_GCM,data:8MsoAeLLFsWDp6KKm15d5gLBFDtBVPWg58YGqO41de6ylODTlYo5Khfm9uqXTnT1sSaQOFmj59ixuVl35bA3EbQdaa/BJXd2O7rufrzNGpyE5tmHsPggMP79PdiZeVeMaAXPvkKc0+0CBuDHlm5O89J+uPHmgxvMmtC2OtVN6Es=,iv:GS7shBf7z5bKLYVq5mZz7ztqBsOqmGte2a4Uz6u22bc=,tag:S2Zkmfhz9AsyO7dxrOQWwg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
