apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6Vcx0ryPrccqskyCbQptDlKB4BRmbcAGNG4vgS8D58/JoUAFqTq7KA==,iv:RelUeYjWiIYiZZ9zfbSdDOgzRYj1i8TSBt+/0A756SQ=,tag:JmCTMVWYBH4eztuXlUrdjA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcHlIdTg4bUVIWGZ1WllY
            UTBiQTdrMHZJWW9JVml4Q0dzc29uZXJHRVZVCjd3TS9Jc1o0b2djSHJtOXA3MkQz
            MjNsVXRJai9RNW9PejBMQWZuUzRlNlkKLS0tIEt0eCtMbFI5VjU3bngwL2xMYlJV
            K3F2ZVRYaHE2TTJNNm1GbzQxdjBGME0KR/UXpOWb6CCOgLX45e8wsjUwMyF6YEg7
            KTdu0WyL8Sef96a0fpo/UAPkbjA/U3G6uBKpbsYKFbygMA7BknXzCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T09:51:59Z"
    mac: ENC[AES256_GCM,data:vyAFR4GG2qo4tM/znBGLSYHWsGAhfYncKow0IGHV4JqpFzDIdImohT3Q031a2dkTr8zq/e8Y4f2+ZdC75lDA4KRp73xf9bo+TKs3zggnWlA8nXkMXxX6EdWunTg/OOaixjvAVpoq42/6p+wg65m62q6YPmnpskVLEmmi4EuC48g=,iv:hQ1pL4AuUP/q8bUqCzfBd/sLks/zToCDkcaNBnqsMNY=,tag:v6ggrj4bmcnGOPjCqLqi9Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
