apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DZlHOmtO13FVmmicY3amo3qyqSX9PXf31M2hjGNWTDUvhsA7u53psp7s5zJ7KSvBygMk4RDkI0NhkYhmtlHviKNXzh/e62qPeVtAMWmKOAFsA7Wrde3v4N2h6fU3y/1POqbC1GoEjwyxbic/y7XCkF6BCFNMzi/5ZlOQIj3x59L+y8eZcGOq1rOrVsjt7h5PG3lueTKGGmRBO41etK68P4UixJV6z3sgZEbBxamlW2MZHrs5Zc2fqn1f6q7hOCOmmdiNpQBHPsOEurDlvBmmGD98dlLCeIFl/e0J2lJMSzb5fOKQdwRthaZpdzEoyYOpHUxcRIrnBaN1oS0VN5H/Dd/iToMCgQMaLqmmuOQPcuWeT7mhO1aZ1NiachxFhuzq,iv:mupAur6FW+p/xWta0yNqRlGVPcCSPdbrAswr9QAha0w=,tag:eLB74TgoSApTu3TZjUyn9w==,type:str]
    identity.pub: ENC[AES256_GCM,data:SdKCTO9GJquNMh3dOHTJqelUYOjofKFDbARFoirK+akwr4Y7uF6i/CplpVzDQago5eU/UbywihBCfF7a7B3sVnrvajOZY4AgGf+zNQfq6emiGzM2ES0NQ+PKQ5gXyxsvYB3z66LizjM61OYjJjnyrGQPWmMRGzrYY5t3+bmSoPPtD4bMbrjYMsAC1sggmvw0gz0vTfZa/pTULyJUhOYFje7PYmlEbyAR1NC8YbByDn+CqD5mzDls4/+ugjp+Prm8kuR+ph0qKnYaNs4f5w==,iv:70CKbPCVj8mXIA7MRfqg7UWuCE1WJv//40a/7uppvKk=,tag:R3V1SpUg45KE/9U1/XD9Lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:eKFd0yjZKVcrh2L/qqo658fvwZHWb66MmOaFCDqKPPoqYOxEvHCaAsPr8BpHzcJhnrIusftFM8FRcAkiTrhEuOsZzNEkQnjkj5c+0BSC5MsjLUCf2ltn8JXjenQ7+fPnh5GkWbZliX+/s4FJSaZVStvg5HUnGRU8JYKa938CXCa24lmYXiDQn852kJanarVGFJkcA+87Lz704iz+PxA42WptgnlBAzNl9gX/,iv:exKqmOUeGJLfF+TWon7mhQ8V8zRDFl9M3SL9RUxr8KY=,tag:MCJR3kI4pLRrbewvrMc9qQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjZOUmc1b0NpVmxwU25Q
            b2JiakltYjBiczdySDIzTXFMZXAvN3Q2ZmprCjFxWXpGUWJBeHk0ZzRaa3VnRm52
            NmV6L2w5RzdXYkVxK0ZHS256ZUhVOGcKLS0tIFlCZEdqUnExRTBOQVpHcUg4WTlK
            K0FwaHRwZTYrUE9xeGFwU1RVRVFtS2cKDkIaH+mTPtpTydqtpYyiXdl2IepsGIrv
            bj1wSzjjELQ5zw83LOMsfPA7QOrDcFIT2/Gl0SL4ZSiE9TA/8GEi4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T09:51:59Z"
    mac: ENC[AES256_GCM,data:cMfCgjz62au20eX0jS6j6YGOLfgVgzJWEehNZ1zbH30SsvicyAF0aOnlsKpbh2mFiWkg3b/X1TY64r+egSgjdPMtUyb2EHB7dL6HQnMvT+6wSEgu+brUfFttZsllKi3sY7pCBaS5RxeAcVvrLxxeVe+CTvhDieeT2jY0cPWyC8w=,iv:SeNHJ8E3Nr8hphk42ir/arBq/vTbDPFLddcvEiGgYtI=,tag:/QBVaxOFfRWlGBwvw1J6hw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
