apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tKDXfCk6u8eHUJ9CgEWgZv3UpcCfcZzuMyT0ePt1R4BJcGT15mXk/KByO47++Cgc4sHJvG1i5+Z+BTGJt2o6e+XPbi383i0c7FFkc1GOrszM4rjdLVQUqz8HXibUO4rph9K6PhKc1ZjQCgD7vLsocQLpjExAlCDmAcoVBspilNaFZ5TWIVnJGyi8Tha5REViLiluTpmkenHDGq54E6sCfRiYu6NzEZ7hSsLUhXITqXKbb/qYsQ78UQR4WyX67AQ76P5T0ZxskQx2UjM92Fi1GAIiEI9wrAQQo9aZsPW9OC+E5WxgSRd3sNEJmReU8OLKEyieoTKO/KZ/PxM5t9IVY8bzTdorgJ+SpxBv3lPvGRx1JlFBNly1hq/mhC83fxTI,iv:egjXbjTT4sMBAZDA40bmalpJi0Rn8J4SB2YtzXxgFx0=,tag:qRRSBG7D5AmwHg4v/E483Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:v7Fat6YfnaMpRxabJJC+lHoqk4RRmg7jjJsLwhmcdwCafCZXG0IHLCd+yjBNT6Ck+3UDXQ1tz6zfIJjZ9QBdSQHp9AWwNUj5Fsd26QeSYpY3Z/uSHaJYLZhuMHpcsqk+x531U8Obifk/9Puf5lxzY+7RgKakFRCQ0I0HzBZtMvEfvgrOCJa4broedovxPYGWgrFjpXgc+5TlRPfYP9ls1SX5O8KdmL7ym7t8adAGCAs3VEogb0qBYOFBVFKq6in7rSgOzIu/qTjSr+Deiw==,iv:0WEaDJJyDJgwIoQM6uTpYTktHnrhZdaM3z24nQDVwFc=,tag:PJjVhs/a5PcQrnYzRuFRjA==,type:str]
    known_hosts: ENC[AES256_GCM,data:SD5R/NxZ8Z9OmF40mavvy5Y55yhp47VxaaeuHHb++xuT0uYjSUez5QnzDGZNe/ZPOzDNQKYgciq80NZ7UW2On09JfwXvh6XkoI6wqkbVfHBSr5+kVo3bPocMVuPy5U93BMLrAFS1mDjxRi6gNmbxfsDHYdag/AJiXFpL6blDypC2ajF5ZVca8FFdeGfHHD8nSJ426y+x8g1fpzaxurCh9REtBAq3tioDt5W4,iv:qvoaHIiq4hE+v0jD+Foqk/id38K/HH9mo6uCihQUoYg=,tag:8zptWqd6dWg+dCc7/rtsHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaFBHZThIaDg2NFUwQW5U
            OURDVUpYejNSVkM0R2dYemRFZ1FUeldtTVVvCng2RE4wcUFDalVleEdrRDY3OXFy
            dEphUE1ZV3dtZFVXZXFqUlZ5N0o1cEUKLS0tIGRqK3B0by96TS8zRTFXNGpTL1pu
            dFVtWXh2UE9ZQm13a3d5cVZ0N08zNVUKZ35NvdtiN6BKh25VeL5XIDiC1CRqZ0bS
            WKV73p11/4WLi6ihHJhALdVTa85f5qP2vu0TAGvhes8ir40ahiDEKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T12:33:57Z"
    mac: ENC[AES256_GCM,data:AkSDmtZNmgUYOQmjMZQEbq8Wr2aKegGnMJ1vqV9t45rkYjnZ7FMedHcYbExGk2cSUDLC8xqLSFdjKzVxgFOMYdaPEo9EUiUyNYH+VQmLS2+rOgFOsm0d4AS1SyLH68wLQQvgvoR9Ttxa8NuiwtAzwzAOMbrvXvLRhbprLK8SseI=,iv:sqf/WJlotlapDOvdeGX7lHtIocpvzVtUlzGfQnaCCXs=,tag:QURf45U/yeSe/Q5aCHQRcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
