apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mv0RnowEDiIA1C1/CWXU1uKJry3ThgIDZV8TVMsnFTvR+3NJq80sxqdYHiP6truM2GRSrFu6veoQmsjUERVc9bl2ofm1TEW50IGw5RfltEoEGohu0KDDKgCbMTj3Y6O1IQYg6ZnZwJr2gRKSlKOBYnqMLJS5JeEeFnV8FRxOtOdG5Q/oAUqNCoGd+TkePcCPpnAUBixVmolrSR4JzuQ1EOM7ayGpvkkyji5nUxA0/DZ9Jtt/uGa7wX4jq/lYcq479b+IpFvK2vLMrumfN8bKc5W+zWlYlNcHIGqmf2ePG9zJEAGsuLVOeYQ3ELKAhvf4IEIplR5WsVGS3fjm7HBGtB0cc0hOuUfgY92gIws8eLeB/cENB5Cc+nIbPIo4YcO5,iv:4W75ggEC8gH8cKIrf9j2JXMwsfNNMDcyskv4M343pNM=,tag:LHuZnS7aICarHjTpdSllEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:kwHiApJB55pGF/nNg+nVmUyje9CCbc5cYNgxZfg0TLcjRB01O4sT9BbWNcWxyJBRDArWdsHw9g3w51VU5RiD6xPKxWbXnOssmBof03rYTvKVCwbJsImg3FMnRiw4Iuq8icoMeCOhg+db/UOkDx3qwcb3pkntu/Z/+AsGC8AlVHEmP2TIF4eFxLYoTp4ZqqYfS8Oi7KiB0BBhv+/T+MgSbowUg6RE2sgJ4ecpFyCuGmPGTHNSaEeomHGFncCX96Diz9bBfeeuSqNTgD0xEA==,iv:ItbsYDYmFnVbVZl4Qc8Lb6VX9f7QDqb/FYbQNrcbBoQ=,tag:zKrcupvgrJuqGktxb7sKmQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:jUdXa3Uwh2q8VlW+h+rlcRivhS7eeEhgFHzJnl0jihGnfz4s/Bx+WQAzyVq65/LBrdGxmZPazQzCTzBbO6DAnRgdMagdc2IHIUKSrF/2lTvFckITkrG8NmlJ5fRXVG/x7rZkw4FSfu52PdcGWhE9UNDE6I0c4OjAUQ2V6JJnp75/ndSG+FNoy+kGIcxA7yMyqqCOd7kO1L6hICBX52+LGvErSCr3RF698ZaO,iv:da5fdofLF31TxraqJwUGBohTWHCYhJkzFN5xUiMifwM=,tag:Eoa+2sowLgChpBI6c5s8+w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldW9sSFJCdVNLY2NhNTVH
            SFI4MjNOVkg5ekIraURQdzVFYUpJUVlFV3prCnNpTVlTTTVUeDhUbXFWVDBPMnoy
            eGxod3AyNFdBZGJ2ZERrYWVTYk01VVEKLS0tIHlqR2wyeDEzUmxlRzNhcUlLcW05
            REEyK1RjdG5EekhzdGgwdTh0dGh1MGMKJQO40dzB1aLhiesU33J9kh+iXMLwICtM
            n1F3HTBmm45E9vU5+oT2x0TOOrhmoOZ5b3CGDC6skZaOvfKqw1r+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:41:08Z"
    mac: ENC[AES256_GCM,data:kmeGE3EsmcGeccKx2NDowqMdSc0jEMVrLUHY4XwJBiIoDxUCRlc/3LI45gBUKRi1B1vLScHqnQburkdRbhR6k0Trbu2Vw6T5iIowHdcEPri+J9+dSq5LSqVY05kZWdye8EZiApaC4taUSa0MnhTIY87ptbu+FpQW0UxRrvURyIE=,iv:hfeBZ+yolwZ4DB3aQqJWl6W3kUYBRIjO0fVJEja+9PQ=,tag:QvHTCfaSYTSaJ3hnuCoW5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
